import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '../../chatgpt-auth';
import {stateSchema,emptyState} from '../../data/state-model';
export const dynamic='force-dynamic';
function db(){if(!env.DB)throw Error('Database unavailable');return env.DB;}

export async function GET(){const user=await getChatGPTUser();if(!user)return Response.json({user:null});try{const row=await db().prepare('SELECT data, revision FROM academy_state WHERE user_id = ?').bind(user.userId).first<{data:string;revision:number}>();const state=row?stateSchema.parse(JSON.parse(row.data)):emptyState();if(!row){const old=await db().prepare('SELECT case_id, completed_at FROM progress WHERE user_id = ?').bind(user.userId).all<{case_id:string;completed_at:number}>();for(const r of old.results)state.completed[r.case_id]=r.completed_at;}return Response.json({user:{id:user.userId,name:user.displayName},state,revision:row?.revision??0});}catch(e){console.error(e);return Response.json({error:'Account storage is unavailable. Your browser draft is safe.'},{status:503});}}
function sameOrigin(r:Request){return r.headers.get('origin')===new URL(r.url).origin;}
export async function POST(r:Request){if(!sameOrigin(r))return Response.json({error:'Invalid origin.'},{status:403});const user=await getChatGPTUser();if(!user)return Response.json({error:'Please sign in again. Your draft is still in this browser.'},{status:401});try{const raw=await r.text();if(raw.length>800000)return Response.json({error:'Saved history is too large. Export a copy before clearing older data.'},{status:413});const input=JSON.parse(raw);const parsed=stateSchema.safeParse(input.state);if(!parsed.success||!Number.isInteger(input.revision)||input.revision<0)return Response.json({error:'Invalid saved data.'},{status:400});const result=await db().prepare('INSERT INTO academy_state (user_id,data,revision,updated_at) VALUES (?,?,1,?) ON CONFLICT(user_id) DO UPDATE SET data=excluded.data, revision=academy_state.revision+1, updated_at=excluded.updated_at WHERE academy_state.revision=?').bind(user.userId,JSON.stringify(parsed.data),Date.now(),input.revision).run();if(!result.meta.changes)return Response.json({error:'Another tab changed your progress. Download your browser draft, then reload before continuing.'},{status:409});return Response.json({revision:input.revision+1});}catch(e){console.error(e);return Response.json({error:'Could not save to your account. Your browser draft is safe.'},{status:503});}}
export async function DELETE(r:Request){if(!sameOrigin(r))return Response.json({error:'Invalid origin.'},{status:403});const user=await getChatGPTUser();if(!user)return Response.json({error:'Sign in first.'},{status:401});try{await db().batch([db().prepare('DELETE FROM academy_state WHERE user_id=?').bind(user.userId),db().prepare('DELETE FROM progress WHERE user_id=?').bind(user.userId),db().prepare('DELETE FROM profiles WHERE user_id=?').bind(user.userId)]);return Response.json({ok:true});}catch(e){console.error(e);return Response.json({error:'Deletion failed. Please retry.'},{status:503});}}
