'use client';
import {useState} from 'react';
import type {AcademyCase,Exhibit as ExhibitType} from './data/case-model';
import {dimensions,lessonIds} from './data/state-model';
import {rubricLevels} from './data/learning';
export function External({href,children}:{href:string;children:React.ReactNode}){return <a className="text-link" href={href} target="_blank" rel="noreferrer">{children}<span aria-label="opens in a new tab"> ↗</span></a>}
export function Exhibit({exhibit}:{exhibit:ExhibitType}){return <div className="exhibit-wrap"><table className="exhibit"><caption>{exhibit.title}<small>{exhibit.units}</small></caption><thead><tr>{exhibit.rows[0].map((s,i)=><th scope="col" key={i}>{s}</th>)}</tr></thead><tbody>{exhibit.rows.slice(1).map((r,i)=><tr key={i}>{r.map((s,j)=>j===0?<th scope="row" key={j}>{s}</th>:<td key={j}>{s}</td>)}</tr>)}</tbody></table></div>}
export function Solution({c}:{c:AcademyCase}){return <div className="solution"><h3>Suggested structure</h3><ul>{c.solution.structure.map(s=><li key={s}>{s}</li>)}</ul><h3>Worked analysis</h3><ol>{c.solution.math.map(s=><li key={s}>{s}</li>)}</ol><div className="callout"><strong>Model answer</strong><p>{c.solution.modelAnswer}</p></div><h3>Recommendation</h3><p>{c.solution.recommendation}</p><h3>Risks</h3><ul>{c.solution.risks.map(s=><li key={s}>{s}</li>)}</ul><h3>Impact lens</h3><p>{c.solution.impactLens}</p></div>}
export function Rubric({c,onSave,disabled=false}:{c:AcademyCase;onSave:(values:number[])=>void;disabled?:boolean}){const [values,setValues]=useState([0,0,0,0,0]);const [saved,setSaved]=useState(false);const valid=values.every(x=>x>0);const weak=values.indexOf(Math.min(...values));return <section className="card panel rubric"><p className="eyebrow">REFLECT & IMPROVE</p><h2>Score the reasoning.</h2><p>Different recommendations can be strong. Judge the evidence and reasoning, not whether your wording matches the guide.</p>{dimensions.map((d,i)=><fieldset key={d}><legend>{d}</legend><div className="rubric-options">{rubricLevels[i].map((s,n)=><label key={n} className={values[i]===n+1?'chosen':''}><input type="radio" name={'rubric-'+i} checked={values[i]===n+1} onChange={()=>{setSaved(false);setValues(a=>a.map((v,j)=>j===i?n+1:v))}}/><strong>{n+1}</strong><span>{s}</span></label>)}</div></fieldset>)}<details><summary>What the levels look like in this case</summary><ol>{c.rubricNotes.map(n=><li key={n}>{n}</li>)}</ol></details>{valid&&<div className="callout"><strong>{values.reduce((a,b)=>a+b,0)} / 20</strong><p>Focus next: {dimensions[weak]}. <a className="text-link" href={'/academy/learn#'+lessonIds[weak]}>Review the related habit →</a></p></div>}<button className="button" disabled={!valid||disabled||saved} onClick={()=>{onSave(values);setSaved(true)}}>{saved?'Score saved':'Save rubric score'}</button></section>}
