import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';import ts from 'typescript';import {pathToFileURL} from 'node:url';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'academy-check-'));
for(const name of ['catalog','new-cases','interviewer','events','learning']){let src=ts.transpileModule(fs.readFileSync(`app/data/${name}.ts`,'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext}}).outputText.replace(/from '\.\/(.*?)'/g,"from './$1.mjs'");fs.writeFileSync(path.join(dir,name+'.mjs'),src);}
const {catalog}=await import(pathToFileURL(path.join(dir,'catalog.mjs')));const {validResponse,clarification}=await import(pathToFileURL(path.join(dir,'interviewer.mjs')));const {events,calendarHref}=await import(pathToFileURL(path.join(dir,'events.mjs')));const {primers,plan}=await import(pathToFileURL(path.join(dir,'learning.mjs')));
assert.equal(catalog.length,32);assert.equal(new Set(catalog.map(c=>c.slug)).size,32);assert.equal(new Set(catalog.map(c=>c.client)).size,32);
for(const c of catalog){assert.notEqual(c.client,c.title);assert.ok(c.title.endsWith('?'));assert.ok(c.clarifyingAnswers.length);assert.equal(c.rubricNotes.length,4);assert.ok(c.solution.impactLens);assert.ok(c.exhibits.every(e=>e.rows.every(r=>r.length===e.rows[0].length)));if(c.difficulty==='Beginner'){assert.ok(c.minutes>=20&&c.minutes<=25);assert.equal(c.exhibits.length,1)}else{assert.ok(c.exhibits.length>=2);assert.ok(c.difficulty==='Intermediate'?c.minutes>=30&&c.minutes<=35:c.minutes>=40&&c.minutes<=45)}}
const counts=Object.fromEntries([...new Set(catalog.map(c=>c.track))].map(t=>[t,catalog.filter(c=>c.track===t).length]));assert.deepEqual(counts,{'Social impact core':16,'Interview fundamentals':10,'Advanced electives':6});const sectors=[...new Set(catalog.map(c=>c.sector))];assert.equal(sectors.length,7);assert.ok(sectors.filter(s=>catalog.filter(c=>c.sector===s).length===1).length<=2);
const pantry=catalog.find(c=>c.id==='pantry');assert.match(clarification(pantry,"what's the current weekly capacity?"),/400 households/);assert.match(clarification(pantry,'What hours are you open?'),/4 days/);assert.match(clarification(pantry,'What is the competitor marketing spend?'),/not something we have data/);
for(let stage=0;stage<5;stage++){assert.equal(validResponse(stage,'banana'),false);assert.equal(validResponse(stage,''),false);assert.equal(validResponse(stage,'banana banana banana banana banana banana banana'),false)}
assert.equal(validResponse(1,'The target gap is 500 minus 400, which equals 100 households per week.'),true);assert.equal(validResponse(4,'I recommend piloting prepacked boxes because they meet the cost and capacity constraints.'),true);
assert.equal(calendarHref(events[0]),'');assert.equal(events[0].registrationUrl,null);assert.ok(calendarHref({...events[0],startTime:'18:00',endTime:'20:00'}).includes('DTSTART'));
// Content quality: no templated filler, and every case carries its own brief, prompts and rubric.
const stop=new Set(['the','a','an','of','in','is','are','and','to','this','that','not','for','with']);
for(const c of catalog){assert.notEqual(c.brief.trim(),c.objective.trim(),c.slug+': brief repeats objective');assert.ok(!c.exhibits.some(e=>e.rows.slice(1).some(r=>r.includes('What would validate this?'))),c.slug+': filler exhibit');assert.ok(!c.rubricNotes.some(n=>n.includes(c.solution.modelAnswer)),c.slug+': rubric pastes model answer');assert.ok(c.furtherReading.length>0,c.slug+': no further reading');for(const a of c.clarifyingAnswers)for(const t of a.topics){assert.match(t,/^[a-z0-9]+$/,c.slug+': bad topic '+t);assert.ok(!stop.has(t),c.slug+': stopword topic '+t)}}
for(const k of ['brainstorm','impactLens'])assert.equal(new Set(catalog.map(c=>c.solution[k])).size,catalog.length,k+' must be case-specific');assert.equal(new Set(catalog.map(c=>c.rubricNotes.join('|'))).size,catalog.length,'rubric notes must be case-specific');
// Natural clarifying questions across cases must return the matching fact.
const T=[['pantry-capacity',"What's the current weekly capacity?",/400 households/],['pantry-capacity','What hours are you open?',/4 days/],['pantry-capacity','What is the budget?',/\$45,000/],['pantry-capacity','How many stations are there?',/Four staffed/],['pantry-capacity','Do clients have internet access?',/internet/],['pantry-capacity','What is the competitor marketing spend?',/not something/],
['refill','How much does the equipment cost?',/\$18,000/],['refill','What do refills cost per unit?',/\$3.80/],['refill','What price would refills sell for?',/\$7.20/],['refill','Do refills attract new customers?',/new customers/],['refill','What is the goal?',/Choose whether/],
['transit','What is the budget?',/\$500,000/],['transit','How many rides do vouchers deliver?',/18,000/],['transit','When do buses stop running?',/10pm/],['transit','How much does the shuttle cost?',/\$460,000/],
['arts','How many visitors come each year?',/30,000/],['arts','What are the fixed costs?',/\$435,000/],['arts','How much do grants bring in?',/\$210,000/],
['clinic','Is there any grant funding?',/foundation/],['clinic','What surplus does the board require?',/\$50,000/],
['software','What is the renewal rate?',/90%/],['software','How much does direct sales cost?',/\$144,000/],['software','What commission do partners get?',/15%/],
['solar','Is there an alternative like a PPA?',/power purchase/],['solar','What is the maintenance cost?',/\$4,000/],['solar','How old is the roof?',/12 years/],
['brightcart','Did labor costs change?',/\$3.56m/],['brightcart','What happened to shrink?',/two percentage/],['brightcart','Did any competitors open?',/no new competitors/],
['novapay','How many households are near the pilot stores?',/30,000/],['novapay','What fee do households pay?',/\$1 per/],['novapay','What does a store cost to run?',/\$50 a week/],
['harborlight','What is the rent?',/\$28/],['harborlight','How many competitors are nearby?',/Three coffee/],['harborlight','What about summer?',/32 term/],
['campus-meals','How many students are there?',/20,000/],['campus-meals','How big is the kitchen?',/5,000/],
['mentoring-outcomes','How many students responded to the survey?',/60 students/],['mentoring-outcomes','Is there a comparison group?',/no comparison/],
['repair-demand','How many jobs did FixLoop do last year?',/900/],['volunteer-shifts','What is the show-up rate?',/80%/],['board-strategy','What is the rental vacancy?',/vacancy/],
['northstar','What is the tax rate?',/25%/],['northstar','How much debt does the target have?',/\$12m/],['lumen','What discount rate should I use?',/10%/],['oakline','Who is the largest payer?',/35%/],['cedar','How many shares does Cedar have?',/10m shares/],
['flexforge','How big is the market?',/\$600 million/],['terraroots','How much does roasting lose in weight?',/18%/],['youth','Is transport needed?',/bus/],['donors','When does the grant end?',/10 months|next year/],['literacy','How much does partner delivery cost?',/\$340/],['merger','Have residents been consulted?',/consultation/],['banking','What fees are charged?',/fee-free/]];
for(const [slug,q,re] of T)assert.match(clarification(catalog.find(c=>c.slug===slug),q),re,slug+': '+q);
for(const p of primers)for(const slug of p.cases)assert.ok(catalog.some(c=>c.slug===slug));for(const w of plan)for(const t of w.tasks)assert.ok(!t.href.includes('elective'));
console.log('PASS: 32 cases, unique slugs and client lines, 7 sectors, 16/10/6 tracks, exhibit shapes, difficulty/time bands, primer links, event gates, clarification matching ('+T.length+' questions), nonsense-response rejection and case-specific content (no filler exhibits, distinct briefs, prompts and rubrics).');
fs.rmSync(dir,{recursive:true});
